<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputPath>..\0Bins\Other\AssetRipper.Export.Modules.Naninovel\$(Configuration)\</OutputPath>
		<IntermediateOutputPath>..\0Bins\obj\AssetRipper.Export.Modules.Naninovel\$(Configuration)\</IntermediateOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\AssetRipper.Import\AssetRipper.Import.csproj" />
	</ItemGroup>

</Project>